### ISSUE TITLE
No theme

### ISSUE THREAD

**Issue by ricdap** [MagistraNocte/Max-8-Default-Dark-Mode#3]
First of all, thanx for your work.
But, I followed the instructions, placed in package folder, I can't see default_dark_mode, I can see only the standard color themes.
MacOSX 11.7.1
Max 8.5.1

What can I do?
Cheers,
Riccardo

**Comment by ricdap** [comment]
Yes, I did. Not tried to reboot cause I'm doing some uploads.
I tried two different Packages folder, both in my search path. Also tried to place directly in the package folder inside Max.app

**Comment by MagistraNocte** [comment]
Putting the folder in the documents/Max 8/Packages folder and relaunching Max should be enough for it to work, unless Cycling '74 changed something in the latest versions of Max (I don't currently have access to 8.5), I don't know if the issue is related to you using more than one package folder (my Shared/Max 8/Library and Shared/Max 8/Packages folders are empty).
This is how mine looks:
![Schermata 2022-12-08 alle 4 10 36 PM](https://user-images.githubusercontent.com/38999587/206482335-c1a5eb16-91fc-4148-8faf-5ac93408aa31.png)

**Comment by ricdap** [comment]
HI. Just installed Max 8.5.2, then I placed the package again in one of my packages folder, and voila it runs perfectly.
Thanks again for your work.
Issue closed
